### ISSUE TITLE
Mixin causing crash with Corail Tombstone

### ISSUE THREAD

**Issue by SHeik-Link** [CravenCraft/BloodyBits#14]
For some reason, this gives me a crash with Corail Tombstone

"java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20148_()" because "this.entity" is null"

 "-- Head --

Thread: Render thread

 Suspected Mods:

 CravenCraft's Bloody Bits (bloodybits), Version: 1.2.1-1.20.1

 
Mixin class: com.cravencraft.bloodybits.mixins.LivingEntityRendererMixin

Target: net.minecraft.client.renderer.entity.LivingEntityRenderer

at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.redirect$ckk000$renderEntitiesDifferently(LivingEntityRenderer.java:4165)"

For some reason this gives me a crash with CravenCraft's Bloody Bits

"java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.LivingEntity.m_20148_()" because "this.entity" is null"

"-- Head --

Thread: Render thread

Suspected Mods:

CravenCraft's Bloody Bits (bloodybits), Version: 1.2.1-1.20.1

Mixin class: com.cravencraft.bloodybits.mixins.LivingEntityRendererMixin

Target: net.minecraft.client.renderer.entity.LivingEntityRenderer

at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.renderer.entity.LivingEntityRenderer.redirect$ckk000$renderEntitiesDifferently(LivingEntityRenderer.java:4165)"

[crash  A-2024-11-10_19.49.10-client.txt](https://github.com/user-attachments/files/17703883/crash.A-2024-11-10_19.49.10-client.txt)

**Comment by CravenCraft** [comment]
Don't worry. I have an update coming out soon that should fix this issue. It's a common one with the latest version. I just didn't have good enough null pointer checks.

**Comment by SHeik-Link** [comment]
ty Craven

**Comment by CravenCraft** [comment]
new version published with the fix. Closing the issue.
